name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: default action in github action official which check repo
      uses: actions/checkout@v3
    - name: we can run commands depends on runs-on os 
      run: |
        date
        echo $GITHUB_REF
        echo $TAG
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: dockerashu/githubactions
       # tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  posttest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    -  name: running post check command
       run: whoami
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        azure_credentials_secret: ${{ secrets.AZURE_CREDENTIALS_SECRET }}
        image: dockerashu/githubactions:latest  # Use the same image name you pushed to Docker Hub
        namespace: default
        deployment: my-app-deployment
