name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CLUSTER_NAME: test-k8s
  CLUSTER_RESOURCE_GROUP: k8sty

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: default action in github action official which check repo
      uses: actions/checkout@v3
    - name: we can run commands depends on runs-on os 
      run: |
        date
        echo $GITHUB_REF
        echo $TAG
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: dockerashu/githubactions
       # tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    -  name: running post check command
       run: whoami
    -  name: setting context 
       uses: azure/aks-set-context@v1
       with:
        creds: '${{ secrets.AZURE_CREDENTIALS_SECRET }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    -  name: Deploy to Kubernetes
       uses: azure/k8s-deploy@v1
       with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
    -  name: upgrading deployment 
       run: kubectl set image deployment web-app githubactions=dockerashu/githubactions:master-"${{ github.sha }}"
