name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CLUSTER_NAME: test-k8s
  CLUSTER_RESOURCE_GROUP: k8sty

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: default action in github action official which check repo
      uses: actions/checkout@v3
    - name: we can run commands depends on runs-on os 
      run: |
        date
        echo $GITHUB_REF
        echo $TAG
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: dockerashu/githubactions
        tags: master-${{ github.sha }}
       # tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: default action in github action official which check repo
      uses: actions/checkout@v3
    - name: running post check command
      run: whoami
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: running command to check credentail 
      run: az group list 
      # just for test only 
    - name: downloading aks kubeconfig file 
      run: az aks get-credentials --resource-group k8sty --name test-k8s --overwrite-existing
    - name: testing kubectl 
      run: kubectl get nodes 
    - name: setting context which will be used by workflow given in below step
      uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: '${{ env.CLUSTER_NAME }}'
        resource-group: '${{ env.CLUSTER_RESOURCE_GROUP }}'
    - name: deploy using manifest 
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          dockerashu/githubactions:master-${{ github.sha }}


